<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.81.0" />


<title>Who Is The Dirtiest Player In The History of MLS? - Peyton Thomas</title>
<meta property="og:title" content="Who Is The Dirtiest Player In The History of MLS? - Peyton Thomas">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/peytonthomas-gh">GitHub</a></li>
    
    <li><a href="https://twitter.com/thepeytonthomas">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">13 min read</span>
    

    <h1 class="article-title">Who Is The Dirtiest Player In The History of MLS?</h1>

    
    <span class="article-date">2021-03-30</span>
    

    <div class="article-content">
      
<script src="/2021/03/30/who-is-the-dirtiest-player-in-the-history-of-mls/index_files/header-attrs/header-attrs.js"></script>


<p>Following the 1994 FIFA World Cup, the U.S Soccer Federation decided it was the right time to create a Division 1 soccer league within the country. Starting play in 1996 with 10 teams, Major League Soccer has now completed 25 seasons and expanded to a whopping 27 clubs, with plans out to 30 by the 2023 season.</p>
<p>Throughout that history, the league has seen a number of aggressive, tough, and physical players pass through the ranks, coming from different countries across the globe.</p>
<p><img src="images/some_pdx_fucker.jfif" style="width:100.0%" /></p>
<p>This is Diego Chara of the Portland Timbers. He was the original inspiration for this quest. Since joining the Timbers in 2011, he has made a career out of playing hardball, many times over the line in the eyes of the official, and of course, rival fans.</p>
<p>But how does Chara stack up to the dirtiest players in league history?</p>
<p>Lets get stuck in.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v ggplot2 3.3.3     v purrr   0.3.4
## v tibble  3.1.1     v dplyr   1.0.5
## v tidyr   1.1.3     v stringr 1.4.0
## v readr   1.4.0     v forcats 0.5.1</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.0.5</code></pre>
<pre><code>## Warning: package &#39;forcats&#39; was built under R version 4.0.5</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(ggrepel)</code></pre>
<pre><code>## Warning: package &#39;ggrepel&#39; was built under R version 4.0.4</code></pre>
<pre class="r"><code>library(ggalt)</code></pre>
<pre><code>## Warning: package &#39;ggalt&#39; was built under R version 4.0.4</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggalt&#39;:
##   method                  from   
##   grid.draw.absoluteGrob  ggplot2
##   grobHeight.absoluteGrob ggplot2
##   grobWidth.absoluteGrob  ggplot2
##   grobX.absoluteGrob      ggplot2
##   grobY.absoluteGrob      ggplot2</code></pre>
<pre class="r"><code>library(gt)</code></pre>
<pre><code>## Warning: package &#39;gt&#39; was built under R version 4.0.4</code></pre>
<pre class="r"><code>MLS &lt;- read_csv(&quot;MLSDP.csv&quot;)</code></pre>
<pre><code>## 
## -- Column specification --------------------------------------------------------
## cols(
##   Player = col_character(),
##   Nation = col_character(),
##   Pos = col_character(),
##   Squad = col_character(),
##   Born = col_double(),
##   X90s = col_double(),
##   CrdY = col_double(),
##   CrdR = col_double(),
##   Fls = col_double()
## )</code></pre>
<p>The lone data set I’m using has been collected through Sports Reference under the “Misc. Stats: Players” data for the MLS. This data set is a collection of every player throughout the 26 year history of the league. The key discipline statistics I’m going to rely on to start comparing each of these players are yellow cards, red cards, and fouls. I also included the number of ‘90s’ each player played in the league, which is more accurate than simple appearances since some players don’t play the full match in each appearance.</p>
<p>First, lets take a look at the Top 10 players in all time bookings, yellow cards and red cards.</p>
<pre class="r"><code>MLS %&gt;% 
  group_by(Player) %&gt;% 
  summarise(
    Reds = sum(CrdR),
    Yellows = sum(CrdY),
    Booking = sum(Reds, Yellows)
  ) %&gt;%
arrange(desc(Booking)) %&gt;% 
  top_n(10)-&gt; MLSSB</code></pre>
<pre><code>## Selecting by Booking</code></pre>
<pre class="r"><code>MLSSBLong &lt;- MLSSB %&gt;% 
  pivot_longer(
    cols=(&quot;Yellows&quot; | &quot;Reds&quot;), 
    names_to=&quot;Bookings&quot;, 
    values_to=&quot;Cards&quot;) %&gt;%
  arrange(desc(Bookings)) %&gt;%
  mutate(BookingOrder = factor(Bookings))</code></pre>
<p>The first question to answer is, which players have been booked more than anyone else?</p>
<pre class="r"><code>ggplot() + 
  geom_bar(data = MLSSBLong, aes(x=reorder(Player, Cards), weight=Cards, fill=BookingOrder)) +
  coord_flip() + 
  scale_fill_manual(values = c(&quot;red&quot;, &quot;gold&quot;)) + 
  theme_minimal() +  
  labs(x=&quot;&quot;, y=&quot;Total Bookings&quot;, title=&quot;With 22 Seasons, Kyle Beckerman Has A Clear Lead In Bookings&quot;, subtitle=&quot;But several others have amassed more red cards than Beckerman in less time.&quot;, caption=&quot;Source: Sports Reference | By Peyton Thomas&quot;)  +
  theme(
    plot.title = element_text(size = 13, face = &quot;bold&quot;),
    axis.title = element_text(size = 10), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
    )</code></pre>
<p><img src="/2021/03/30/who-is-the-dirtiest-player-in-the-history-of-mls/index_files/figure-html/unnamed-chunk-4-1.png" width="672" />
Beckerman, of course Beckerman. Kyle Beckerman, the Real Salt Lake midfielder with legs of steel. Our friend Diego Chara also managed to finish runner up. So is that it then? Is Beckerman clearly the dirtiest player in MLS?</p>
<p>Well not exactly, this model favors players who have managed to play more minutes within the league, since there is no basis that can balance these bookings against how long each player has played. Kyle Beckerman with an outstanding 22 seasons and 457.4 ‘90s’ has a significant advantage over everyone else. Chara also hasn’t done too bad for himself with 10 seasons and 275 ‘90s’.</p>
<p>If these players have played so many games compared to everyone else, what is the average amount of appearances and specifically yellow cards for your Average Joe?</p>
<p>First, lets take out Goalkeepers, since no one really cares about the “time wasting” yellows that they seldom pick up.</p>
<p>We can also remove the players in our dataset who have never taken the field to play a single minute.</p>
<pre class="r"><code>FieldPlayers &lt;- c(&quot;DF&quot;, &quot;DFMF&quot;, &quot;FW&quot;, &quot;FWDF&quot;, &quot;FWMF&quot;, &quot;FWGK&quot;, &quot;MF&quot;, &quot;MFDF&quot;, &quot;MFFW&quot;)</code></pre>
<pre class="r"><code>MLS %&gt;% 
  group_by(Player) %&gt;% 
  filter(
    X90s &gt; 0,
    Pos %in% FieldPlayers) %&gt;%
  summarize(
    Games = sum(`X90s`),
    YellowCards = sum(CrdY)) -&gt; MLSAPP</code></pre>
<p>Perfect, now lets find the medians for what we have left.</p>
<pre class="r"><code>MLSAPP %&gt;% summarize(
  `Median Games` = median(Games),
  `Median Yellows` = median(YellowCards))</code></pre>
<pre><code>## # A tibble: 1 x 2
##   `Median Games` `Median Yellows`
##            &lt;dbl&gt;            &lt;dbl&gt;
## 1           17.9                3</code></pre>
<p>A little below 18 ‘90s’ paired with just 3 yellow cards for our Average Joe. A far sight from Beckerman’s tally.</p>
<p>Lets throw those median values into context, by grouping together all our Average Joes, which includes all field players who have played at least one minute.</p>
<pre class="r"><code>MLS %&gt;% group_by(Player) %&gt;% 
  filter(
    X90s &gt; 0,
    Pos %in% FieldPlayers) %&gt;%
  summarize(
    Bookings = sum(CrdY + CrdR),
    Years = n(),
    Games = sum(X90s),
    BPG = mean(Bookings/Games)) -&gt; MLSAJ</code></pre>
<p>Throughout his career, Beckerman has amassed an impressive ~0.289 bookings per game. Which has helped him pull away on the all time leaderboard. However lets tally how many experienced players have an even higher Bookings/Game rate than our bookings leader.</p>
<p>We’ll also create a dataframe for Beckerman himself.</p>
<pre class="r"><code>MLSAJ %&gt;% filter(
  Years &gt; 5,
  Games &gt; 100,
  BPG &gt; .28858
) -&gt; MLSFPD</code></pre>
<pre class="r"><code>MLSAJ %&gt;% filter(Player == &quot;Kyle Beckerman&quot;) -&gt; KB</code></pre>
<pre class="r"><code>ggplot() + 
  geom_point(
    data=MLSAJ, 
    aes(x=Games, y=Bookings, size=Years), 
    color=&quot;grey&quot;, 
    alpha=.5) + 
  geom_point(
    data=MLSFPD, 
    aes(x=Games, y=Bookings, size=Years), 
    color=&quot;#013A81&quot;,
    alpha=.8) + 
  geom_point(
    data=KB, 
    aes(x=Games, y=Bookings, size=Years), 
    color=&quot;#B30838&quot;) +
  geom_text_repel(
    data=KB, 
    aes(x=Games, y=Bookings, label=Player)
  ) + geom_smooth(data=MLSAJ, aes(x=Games, y=Bookings), method=&quot;lm&quot;) + theme_minimal() +  
  labs(title=&quot;Kyle Beckerman Is Still The Bookings King&quot;, subtitle=&quot;However, 25 players with heavy experience surpass Beckerman in bookings per match.&quot;, caption=&quot;Source: Sports Reference | By Peyton Thomas&quot;)  +
  theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    axis.title = element_text(size = 8), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
    )</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/2021/03/30/who-is-the-dirtiest-player-in-the-history-of-mls/index_files/figure-html/unnamed-chunk-11-1.png" width="672" />
The blue line separates the median number of Bookings/Game created from our Average Joe. All players below the line are relatively “clean”, while players above the line are “dirty” compared to the average.</p>
<p>Clearly, Beckerman is in a league of his own in terms of games and yellows combined. But using his clubs colors, there are more than 2 dozen players in blue, that not only have a great wealth of experience, but also a greater Bookings/Game rate than Beckerman. It may not be so clear after all.</p>
<p>Lets leave everyone at the mercy of the same jury, by creating a “Dirtyness Rating” for every eligible player.</p>
<p>In order to be the dirtiest player in MLS history, you must be Notorious. In this case, that means playing more than 68 ‘90s’. Why 68? Well there are 34 games in an MLS season so 68 ‘90s’ would be 2 full seasons on the pitch. At least 10 different bookings, and finally, seperate appearances in at least 3 different seasons throughout each players MLS career.</p>
<pre class="r"><code>Notorious &lt;- MLS %&gt;% group_by(Player) %&gt;%
  summarize(
    Bookings = sum(CrdY + CrdR),
    Years = n(),
    Games = sum(X90s),
    YPG = mean(CrdY/Games),
    RPG = mean(CrdR/Games),
    FPG = mean(Fls/Games)) %&gt;%
  filter(Games &gt; 68,
         Bookings &gt; 10,
         Years &gt; 2) %&gt;%
  ungroup()</code></pre>
<p>Along with filtering our Notorious players, I also created average discipline ratings per game for each player, to help limit the advantage for a higher number of appearances. Leaving us with just 539 candidates to become the “Dirtiest Player in the History of MLS.”</p>
<p>We are almost ready to throw our players into our formula, however lets slide into one more reckless factor. A name bonus.</p>
<p>There is an interesting phenomenon in MLS that players who have played in the league with a name starting with “Diego C” carry a reputation of being extremely dirty, compared to other players whose names do not start with “Diego C”.</p>
<p>So lets award all players who have a name that starts with “Diego C” a 1 point bonus in our formula.</p>
<pre class="r"><code>Notorious %&gt;% 
  mutate(Bonus = case_when(
  grepl(&quot;Diego C&quot;, Player) ~ 1, 
  grepl(&quot;&quot;, Player) ~ 0)) -&gt; NameBonus</code></pre>
<p>Here we go, its time to throw every eligible player through our “Dirtyness Formula” which reads as follows.</p>
<p>Dirtyness Rating = (((YPG<em>.34 + RPG</em>1.7 + FPG<em>.017)</em>(Games^.7))*5+(Bonus))</p>
<p>Yellows/Game, Reds/Game, and Fouls/Game have all been weighted based on how often they occur in a match, and how ‘dirty’ each type of action is perceived. For example, a red card is going to improve your dirtyness rating more than a common foul.</p>
<p>These three values are then added together and multiplied by an exponential function Games^.7. This function provides a slight advantage to players who have played more games in the MLS. Essentially, experienced players are slightly dirtier since they have done it for longer.</p>
<p>Then, our value is multiplied by 5. The last step is to simply add in our bonus. Remember, all players with a name starting with “Diego C” will receive a 1 point bonus in their final Dirtyness Rating.</p>
<p>Okay, lets do this thing.</p>
<pre class="r"><code>Dirtyness &lt;- NameBonus %&gt;% group_by(Player) %&gt;%
  mutate(DirtynessRating = (((YPG*.34 + RPG*1.7 + FPG*.017)*(Games^.7))*5+(Bonus))) %&gt;%
  ungroup()</code></pre>
<pre class="r"><code>Top10 &lt;- Dirtyness %&gt;%
 arrange(desc(DirtynessRating)) %&gt;% 
  top_n(10, wt=DirtynessRating) </code></pre>
<pre class="r"><code>Top10 %&gt;% 
  select(Player, Years, Games, DirtynessRating) %&gt;% 
  rename(`90s` = Games, `Dirtyness Rating` = DirtynessRating) %&gt;% 
  gt() %&gt;%
  tab_header(
    title = &quot;Behind An Impressive Brigade Of Red Cards, Cole Tops The Pack&quot;,
    subtitle = &quot;Diego Chara of the Portland Timbers also cracks the Top 5 in dirtiest players in history of the league, using an absolutely fair, 100% objective, non-bias model.&quot;
  ) %&gt;% tab_style(
    style = cell_text(color = &quot;black&quot;, weight = &quot;bold&quot;, align = &quot;left&quot;),
    locations = cells_title(&quot;title&quot;)
  ) %&gt;% tab_style(
    style = cell_text(color = &quot;black&quot;, align = &quot;left&quot;),
    locations = cells_title(&quot;subtitle&quot;)
  ) %&gt;%
  tab_source_note(
    source_note = &quot;Source: Sports Reference | By Peyton Thomas&quot;
  ) %&gt;% tab_style(
    style = cell_text(color = &quot;black&quot;, weight = &quot;bold&quot;),
    locations = cells_body(
      columns = vars(Player)
    )
  ) %&gt;% 
  tab_style(
    style = cell_text(color = &quot;black&quot;, weight = &quot;normal&quot;),
    locations = cells_body(
      columns = vars(Years),
    )
  ) %&gt;% 
  tab_style(
    style = cell_text(color = &quot;black&quot;, weight = &quot;normal&quot;),
    locations = cells_body(
      columns = vars(`90s`),
    )
  ) %&gt;% 
  tab_style(
    style = cell_text(color = &quot;black&quot;, weight = &quot;normal&quot;),
    locations = cells_body(
      columns = vars(`Dirtyness Rating`),
      rows = `Dirtyness Rating` &lt; 6.9
    )
  ) %&gt;% 
  tab_style(
    style = cell_text(color = &quot;red&quot;, weight = &quot;bold&quot;),
    locations = cells_body(
      columns = vars(`Dirtyness Rating`),
      rows = `Dirtyness Rating` &gt; 6.9
    )
  ) %&gt;% 
  opt_row_striping() %&gt;% 
  opt_table_lines(&quot;none&quot;) %&gt;% 
  tab_style(
    style = cell_borders(sides = c(&quot;top&quot;, &quot;bottom&quot;), 
                         color = &quot;grey&quot;, weight = px(1)),
    locations = cells_column_labels(everything())
  )</code></pre>
<pre><code>## Warning: The `.dots` argument of `group_by()` is deprecated as of dplyr 1.0.0.</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#sznxchwxdr .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: none;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#sznxchwxdr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sznxchwxdr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#sznxchwxdr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#sznxchwxdr .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sznxchwxdr .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sznxchwxdr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#sznxchwxdr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#sznxchwxdr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#sznxchwxdr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#sznxchwxdr .gt_column_spanner {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#sznxchwxdr .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#sznxchwxdr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#sznxchwxdr .gt_from_md > :first-child {
  margin-top: 0;
}

#sznxchwxdr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#sznxchwxdr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: none;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#sznxchwxdr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#sznxchwxdr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sznxchwxdr .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#sznxchwxdr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sznxchwxdr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: none;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#sznxchwxdr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#sznxchwxdr .gt_table_body {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sznxchwxdr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sznxchwxdr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#sznxchwxdr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sznxchwxdr .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#sznxchwxdr .gt_left {
  text-align: left;
}

#sznxchwxdr .gt_center {
  text-align: center;
}

#sznxchwxdr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#sznxchwxdr .gt_font_normal {
  font-weight: normal;
}

#sznxchwxdr .gt_font_bold {
  font-weight: bold;
}

#sznxchwxdr .gt_font_italic {
  font-style: italic;
}

#sznxchwxdr .gt_super {
  font-size: 65%;
}

#sznxchwxdr .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="sznxchwxdr" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="4" class="gt_heading gt_title gt_font_normal" style="color: black; text-align: left; font-weight: bold;">Behind An Impressive Brigade Of Red Cards, Cole Tops The Pack</th>
    </tr>
    <tr>
      <th colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="color: black; text-align: left;">Diego Chara of the Portland Timbers also cracks the Top 5 in dirtiest players in history of the league, using an absolutely fair, 100% objective, non-bias model.</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Player</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Years</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">90s</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Dirtyness Rating</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Ashley Cole</td>
      <td class="gt_row gt_center" style="color: black; font-weight: normal;">3</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">82.4</td>
      <td class="gt_row gt_right" style="color: red; font-weight: bold;">6.908997</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Simo Valakari</td>
      <td class="gt_row gt_center gt_striped" style="color: black; font-weight: normal;">3</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">82.0</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">6.586732</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Leandro González Pirez</td>
      <td class="gt_row gt_center" style="color: black; font-weight: normal;">4</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">108.0</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">6.436458</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Cristian Higuita</td>
      <td class="gt_row gt_center gt_striped" style="color: black; font-weight: normal;">5</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">80.8</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">5.831424</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Diego Chará</td>
      <td class="gt_row gt_center" style="color: black; font-weight: normal;">10</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">275.0</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">5.634111</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Leonel Álvarez</td>
      <td class="gt_row gt_center gt_striped" style="color: black; font-weight: normal;">6</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">123.0</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">5.594897</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Jack Price</td>
      <td class="gt_row gt_center" style="color: black; font-weight: normal;">3</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">69.8</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">5.557239</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Aníbal Godoy</td>
      <td class="gt_row gt_center gt_striped" style="color: black; font-weight: normal;">6</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">112.6</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">5.487606</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Matías Laba</td>
      <td class="gt_row gt_center" style="color: black; font-weight: normal;">5</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">122.4</td>
      <td class="gt_row gt_right" style="color: black; font-weight: normal;">5.401492</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Kendall Waston</td>
      <td class="gt_row gt_center gt_striped" style="color: black; font-weight: normal;">7</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">152.7</td>
      <td class="gt_row gt_right gt_striped" style="color: black; font-weight: normal;">5.276071</td>
    </tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="4">Source: Sports Reference | By Peyton Thomas</td>
    </tr>
  </tfoot>
  
</table></div>
<p>Ashley Cole played 3 seasons in MLS for a combined 82.4 ‘90s’. He didn’t clear the “Notorious” requirement by much, but he certainly left his mark on MLS with a crusade of dangerous challenges. With an impressive 0.0243 Red Cards/Game rate, almost twice as high as any other player, Cole has the highest Dirtyness Rating in the league at ~6.91, a margin of over 0.3 or 5% from Valakari, the runner-up. Cole was able to collect 6 red cards during his comparatively short spell in MLS, those 6 reds were also a whopping 33% of his total bookings, much higher than the average. In just 3 seasons, Cole was suspended for 9 separate games due to his proclivity for discipline.</p>
<p>Our friend Diego Chara also made his mark, coming in at the number 5 spot. With 275 ‘90s’ Chara has significantly more experience in the league than any other player who was able to crack the Top 10.</p>
<p>In the end, the title of “Dirtiest Player in the History of the MLS” goes to a player who made a name for his tough play on a different continent, before entering into MLS. Ashley Cole, congratulations, you earned it.</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
  </body>
</html>

